---
# - name: Update all Packages
#   yum: 
#     name: '*'
#     state: latest

- name: Install developer tools
  yum:
    name: 
      - tree
      - vim 
      - git
    state: present 

- name: Git clone, my repo 
  ansible.builtin.git: 
    repo: "{{ git_project }}"
    dest: "/home/vagrant/{{ project_name }}"