Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.network "forwarded_port", guest: 80, host: 8086
    config.vm.synced_folder ".", "/vagrant"

    ####### Provision #######
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/playbook.yaml"
      ansible.verbose = true
    end
  end